name: issue-welcome

on:
  issues:
    types: [opened] #Solo se activa cuando se crea un issue

permissions:
  issues: write

jobs:
  issue-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Siturar en el repositorio
        uses: actions/checkout@v4
      - name: Comentar en el issue
        run: |
         gh issue comment ${{github.event.issue.number}} \
         --body "Hola ${{github.actor}} gracias por tu reporte"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}