name: pr

on:
    pull_request:
        types: [opened]

permissions:
    pull-requests: write

jobs:
    pr-comment-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Situar en repo
              uses: actions/checkout@v4
            - name: Obtener Datos de PR
              env:
                GH_TOKEN: ${{github.token}}
              run: gh pr comment ${{github.event.pull_request.number}} --body "Hola ${{github.actor}} tu pr esta en revision ðŸš€"