name: push
on:
    push:

permissions:
    contents: write

jobs:
    push-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4
            
            - name: SETUP Git
              run: | 
               git config --global user.email "github-actions[bot]@users.noreply.github.com"
               git config --global user.name "github-actions[bot]"

            - name: "Edit README"
              run: echo "README editado el $(date) por ${{github.actor}}, el id del commit es ${{github.event.commits.id}}" > README.md
              env:
                GH_TOKEN: ${{github.token}}

            - name: "Haciendo push de los cambios"
              run: git add . && git commit -m "UPDATE README" && git push origin main