name: push
on:
    push:

permissions:
    contents: write

jobs:
    push-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4
            
            - name: "Edit README"
              run: echo "README editado el $(date) por ${{github.actor}}" > README.md
              env:
                GH_TOKEN: ${{github.token}}
            - name: "Haciendo push de los cambios"
              run: git add . && git commit -m "UPDATE README"