name: chequeo-seguridad

on:
    schedule:
        - cron: '56 9 10 1 *'

jobs:
    security-check:
        runs-on: ubuntu-latest
        steps:
            - name: Ejecutar scanner
              run: echo "Ejecutando Scaneo..." && echo "Scaneo exitoso"