on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: WhatsApp Notification
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.ACCOUNT_SID }}/Messages.json \
          --data-urlencode "From=whatsapp:+14155238886" \
          --data-urlencode "To=whatsapp:${{ secrets.TO_WHATSAPP_NO }}" \
          --data-urlencode "Body=Nuevo commit hecho por ${{github.actor}}" \
          -u "${{ secrets.ACCOUNT_SID }}:${{ secrets.AUTH_TOKEN }}"
      
      - name: Run
        run: |
          echo 'Mensaje enviado!'
