on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: WhatsApp Notification
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.ACCOUNT_SID }}/Messages.json \
          --data-urlencode "From=whatsapp:+14155238886" \
          --data-urlencode "To=whatsapp:${{ secrets.TO_WHATSAPP_NO }}" \
          --data-urlencode "Body=Nuevo commit hecho en ${{github.repository}}
          üßî Autor: ${{github.actor}}
          üå≥ Branch: ${{github.ref_name}}
          ‚úâÔ∏è Message: ${{github.event.head_commit.message}}" \
          -u "${{ secrets.ACCOUNT_SID }}:${{ secrets.AUTH_TOKEN }}"
      
      - name: Run
        run: |
          echo 'Mensaje enviado!'
